Repository suk05112/Habit-Management, pull requests merged in 2025-06, with the labels that each got.

#7 [ECS 14] HabitColor 구현
  Habit Management/Core/Extension/Color.swift
  Habit Management/Core/ViewModifier/FillColorModifier.swift
  Habit Management/Feature/Calendar/CalendarBackground/CalendarBackgroundView.swift
  Habit Management/Feature/Calendar/CalendarGrid/CalendarGridView.swift
  Habit Management/Feature/Calendar/CalendarLevel/CalendarLevelView.swift
  Habit Management/Feature/Calendar/CalendarScrollView.swift
  Habit Management/Feature/Habit/HabitBackground/HabitBackgroundView.swift
  Habit Management/Feature/Habit/HabitHeader/HabitHeaderView.swift
  Habit Management/Feature/Habit/HabitView.swift
  Habit Management/Feature/Statistics/View/Scroll/ThisWeekView.swift
Labels: 💄 STYLE

#8 [ECS 8 Structure] 자잘한 이슈 수정
  Habit Management.xcodeproj/project.pbxproj
  Habit Management.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Habit Management.xcodeproj/project.xcworkspace/xcuserdata/hansujin.xcuserdatad/UserInterfaceState.xcuserstate
  Habit Management/Core/Extension/Date.swift
  Habit Management/Core/Extension/String.swift
  Habit Management/Feature/Habit/CompletionClient.swift
  Habit Management/Feature/Habit/CompletionFeature.swift
  Habit Management/Feature/Habit/HabitClient.swift
  Habit Management/Feature/Statistics/StatisticsClient.swift
  Habit Management/Feature/Statistics/StatisticsFeature.swift
  Habit Management/Feature/Statistics/View/Graph.swift
  Habit Management/Feature/Statistics/View/StatisticsView.swift
  Habit Management/Feature/Statistics/View/TotalView.swift
  Habit Management/Habit_ManagementApp.swift
  Habit Management/Model/ReportData.swift
  Habit Management/Model/Statistics.swift
  HabitVM.swift
  StaticVM.swift
  compltedLIstVM.swift
Labels: 🏗️ CHORE

#9 [ECS 17] Habit ScrollView, AddButton 리팩토링
  Add/AddView.swift
  Habit Management.xcodeproj/project.pbxproj
  Habit Management/App/AppFeature.swift
  Habit Management/Core/Component/RoundedCorner.swift
  Habit Management/Core/Extension/Date.swift
  Habit Management/Core/Extension/DateFormatter.swift
  Habit Management/Core/Extension/View.swift
  Habit Management/Core/Model/Mode.swift
  Habit Management/Core/Support/DateFormatters.swift
  Habit Management/Feature/Calendar/CalendarGrid/CalendarGridFeature.swift
  Habit Management/Feature/Calendar/CalendarGrid/CalendarGridView.swift
  Habit Management/Feature/Calendar/CalendarView.swift
  Habit Management/Feature/Habit/CompletionClient.swift
  Habit Management/Feature/Habit/HabitClient.swift
  Habit Management/Feature/Habit/HabitFeature.swift
  Habit Management/Feature/Habit/HabitHeader/HabitHeaderView.swift
  Habit Management/Feature/Habit/HabitScroll/HabitItem/HabitItemView.swift
  Habit Management/Feature/Habit/HabitScroll/HabitScrollView.swift
  Habit Management/Feature/Habit/HabitToggleView/HabitToggleFeature.swift
  Habit Management/Feature/Habit/HabitToggleView/HabitToggleView.swift
  Habit Management/Feature/Habit/HabitView.swift
  Habit Management/Feature/Statistics/View/AnimationView.swift
  Habit Management/Feature/Statistics/View/ReportView.swift
  Habit Management/Model/Habit.swift
  Item/ItemView.swift
  MainView.swift
Labels: 🔧 REFACTOR, ✨ FEAT, 🏗️ CHORE, 💄 STYLE
